# Generated by Django 5.1.5 on 2025-02-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
