# Generated by Django 5.0.10 on 2025-02-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_image_book_pdf_book_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='overkill.jpg', null=True, upload_to='upload/'),
        ),
    ]
