# Generated by Django 5.1.5 on 2025-02-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariox',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
