# Generated by Django 5.1.5 on 2025-02-19 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_albuminstance_cuandosereservo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albuminstance',
            name='cuandoSeReservo',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='whenWasItBooked',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
